In [3]:
import pandas as pd
data = {
    "Tid": [1,2,3,4,5,6,7,8,9,10],
    "Refund": ["Yes","No","No","Yes","No","No","Yes","No","No","No"],
    "Marital Status": ["Single","Married","Single","Married","Divorced","Married","Divorced","Single","Married","Single"],
    "Taxable Income": ["125K","100K","70K","120K","95K","60K","220K","85K","75K","90K"],
    "Cheat": ["No","No","No","No","Yes","No","No","Yes","No","Yes"]
}
df = pd.DataFrame(data)
df

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

In [11]:
df.loc[[0,4,7,8]]

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

In [12]:
df.loc[3:7]
df.iloc[4:9, 2:5]
df.iloc[:, 1:4]

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

In [10]:
iris = pd.read_csv("C:/Users/gupta/Downloads/Iris.csv") 
iris.head()

<class 'FileNotFoundError'>: [Errno 44] No such file or directory: 'C:/Users/gupta/Downloads/Iris.csv'

In [ ]:
iris_mod = iris.drop(index=4)          # delete row 4
iris_mod = iris_mod.drop(iris_mod.columns[3], axis=1)   # delete column 3
iris_mod.head()

In [13]:
employees = {
    "Employee_ID":[101,102,103,104,105],
    "Name":["Alice","Bob","Charlie","Diana","Edward"],
    "Department":["HR","IT","IT","Marketing","Sales"],
    "Age":[29,34,41,28,38],
    "Salary":[50000,70000,65000,55000,60000],
    "Years_of_Experience":[4,8,10,3,12],
    "Joining_Date":["2020-03-15","2017-07-19","2013-06-01","2021-02-10","2010-11-25"],
    "Gender":["Female","Male","Male","Female","Male"],
    "Bonus":[5000,7000,6000,4500,5000],
    "Rating":[4.5,4.0,3.8,4.7,3.5]
}

emp_df = pd.DataFrame(employees)
emp_df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [14]:
#a
emp_df.shape
#b
emp_df.info()
#c
emp_df.describe()
#d
emp_df.head()
emp_df.tail(3)
#e
emp_df["Salary"].mean()          
emp_df["Bonus"].sum()            
emp_df["Age"].min()              
emp_df["Rating"].max()  
#f
emp_df.sort_values(by="Salary", ascending=False)
#g
def categorize(r):
    if r >= 4.5:
        return "Excellent"
    elif r >= 4.0:
        return "Good"
    else:
        return "Average"
emp_df["Performance"] = emp_df["Rating"].apply(categorize)
emp_df
#h
emp_df.isnull().sum()
#i
emp_df.rename(columns={"Employee_ID":"ID"}, inplace=True)
#j
emp_df[emp_df["Years_of_Experience"] > 5]
emp_df[emp_df["Department"] == "IT"]
#k
emp_df["Tax"] = emp_df["Salary"] * 0.10
emp_df
#l
emp_df.to_csv("employees_modified.csv", index=False)

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      str
 2   Department           5 non-null      str
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      str
 7   Gender               5 non-null      str
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), str(4)
memory usage: 392.0 bytes